In [20]:
import numpy as np
import pandas as pd

### Data Processing

In [4]:
patients = pd.read_csv('patients.csv')
diagnoses = pd.read_csv('diagnoses.csv')
outcomes = pd.read_csv('outcomes.csv')
labs = pd.read_csv('labs.csv')

In [5]:
patients

,PatientID,Name,Age,Gender,DiagnosisID,AdmissionDate,DischargeDate,OutcomeID,TreatmentCost
0,1,Edward Montes,68,M,2,2025-03-22,2025-04-04,1,4443
1,2,Jessica Zimmerman,81,M,2,2025-03-31,2025-04-02,2,4265
2,3,Gina Alexander,58,M,6,2025-01-08,2025-03-13,1,4188
3,4,Lori Green,44,F,3,2025-04-03,2025-04-05,1,9783
4,5,Jack Logan,72,F,9,2025-06-03,2025-06-04,1,5005
...,...,...,...,...,...,...,...,...,...
195,196,Shelly Dominguez,72,M,10,2025-04-28,2025-05-02,3,3311
196,197,Destiny Johnson,58,M,2,2025-03-06,2025-07-08,3,5191
197,198,Catherine Case,65,M,3,2025-05-26,2025-06-04,2,8957
198,199,Dennis Wolfe,42,F,2,2025-06-26,2025-07-05,2,4538
199,200,Gregory Bates,61,F,3,2025-01-11,2025-03-09,3,5983

In [6]:
diagnoses

   DiagnosisID   DiagnosisName
0            1    Hypertension
1            2        Diabetes
2            3   Heart Disease
3            4          Asthma
4            5          Stroke
5            6            COPD
6            7          Cancer
7            8       Arthritis
8            9  Kidney Disease
9           10   Liver Disease

In [7]:
outcomes

   OutcomeID  OutcomeName
0          1    Recovered
1          2  Complicated
2          3     Deceased

In [8]:
labs

     LabID  PatientID        TestName  Result NormalRange
0        1        196  Blood Pressure    89.7     150-200
1        2        165     Cholesterol   270.2       13-17
2        3        182  Blood Pressure   268.0     0.6-1.2
3        4        142     Cholesterol    57.3     150-200
4        5         55     Blood Sugar   256.5      120/80
..     ...        ...             ...     ...         ...
195    196        176     Cholesterol   194.7      70-120
196    197         72      Hemoglobin   159.7       20-50
197    198         59  Blood Pressure   231.3      70-120
198    199         82      Creatinine   171.7       13-17
199    200        116      Hemoglobin   268.4     150-200

[200 rows x 5 columns]

### EDA

In [25]:
patients.shape

(200, 14)

In [30]:
patients.columns

Index(['PatientID', 'Name', 'Age', 'Gender', 'DiagnosisID', 'AdmissionDate',
       'DischargeDate', 'OutcomeID', 'TreatmentCost', 'DiagnosisName_x',
       'DiagnosisName_y', 'OutcomeName', 'Length_of_Stay', 'OutcomeEncoded'],
      dtype='object')

In [26]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PatientID        200 non-null    int64
 1   Name             200 non-null    object
 2   Age              200 non-null    int64
 3   Gender           200 non-null    object
 4   DiagnosisID      200 non-null    int64
 5   AdmissionDate    200 non-null    datetime64[ns]
 6   DischargeDate    200 non-null    datetime64[ns]
 7   OutcomeID        200 non-null    int64
 8   TreatmentCost    200 non-null    int64
 9   DiagnosisName_x  200 non-null    object
 10  DiagnosisName_y  200 non-null    object
 11  OutcomeName      200 non-null    object
 12  Length_of_Stay   200 non-null    int64
 13  OutcomeEncoded   200 non-null    int64
dtypes: datetime64[ns](2), int64(7), object(5)
memory usage: 22.0+ KB

In [28]:
patients.describe()

,PatientID,Age,DiagnosisID,AdmissionDate,DischargeDate,OutcomeID,TreatmentCost,Length_of_Stay,OutcomeEncoded
count,200.000000,200.00000,200.000000,200,200,200.000000,200.000000,200.000000,200.000000
mean,100.500000,59.32500,5.245000,2025-04-09 06:21:36,2025-05-08 10:12:00,2.030000,6104.910000,29.160000,0.685000
min,1.000000,30.00000,1.000000,2025-01-01 00:00:00,2025-01-14 00:00:00,1.000000,2054.000000,1.000000,0.000000
25%,50.750000,44.00000,3.000000,2025-02-24 12:00:00,2025-04-11 18:00:00,1.000000,4415.250000,4.000000,0.000000
50%,100.500000,58.50000,5.000000,2025-04-19 00:00:00,2025-05-19 00:00:00,2.000000,5929.500000,9.000000,1.000000
75%,150.250000,73.00000,8.000000,2025-05-25 00:00:00,2025-06-09 06:00:00,3.000000,7963.000000,49.000000,1.000000
max,200.000000,89.00000,10.000000,2025-06-30 00:00:00,2025-07-10 00:00:00,3.000000,9973.000000,169.000000,1.000000
std,57.879185,17.39027,2.971384,NaN,NaN,0.813887,2201.939376,37.585472,0.465682

In [31]:
patients.isna().sum()

PatientID          0
Name               0
Age                0
Gender             0
DiagnosisID        0
AdmissionDate      0
DischargeDate      0
OutcomeID          0
TreatmentCost      0
DiagnosisName_x    0
DiagnosisName_y    0
OutcomeName        0
Length_of_Stay     0
OutcomeEncoded     0
dtype: int64

In [33]:
patients[patients.duplicated()]

Empty DataFrame
Columns: [PatientID, Name, Age, Gender, DiagnosisID, AdmissionDate, DischargeDate, OutcomeID, TreatmentCost, DiagnosisName_x, DiagnosisName_y, OutcomeName, Length_of_Stay, OutcomeEncoded]
Index: []

In [11]:
patients = patients.merge(diagnoses, on='DiagnosisID')
patients = patients.merge(outcomes, on='OutcomeID')

In [12]:
patients.head(5)

,PatientID,Name,Age,Gender,DiagnosisID,AdmissionDate,DischargeDate,OutcomeID,TreatmentCost,DiagnosisName_x,DiagnosisName_y,OutcomeName
0,1,Edward Montes,68,M,2,2025-03-22,2025-04-04,1,4443,Diabetes,Diabetes,Recovered
1,2,Jessica Zimmerman,81,M,2,2025-03-31,2025-04-02,2,4265,Diabetes,Diabetes,Complicated
2,3,Gina Alexander,58,M,6,2025-01-08,2025-03-13,1,4188,COPD,COPD,Recovered
3,4,Lori Green,44,F,3,2025-04-03,2025-04-05,1,9783,Heart Disease,Heart Disease,Recovered
4,5,Jack Logan,72,F,9,2025-06-03,2025-06-04,1,5005,Kidney Disease,Kidney Disease,Recovered

In [13]:
patients['AdmissionDate'] = pd.to_datetime(patients['AdmissionDate'])
patients['DischargeDate'] = pd.to_datetime(patients['DischargeDate'])

In [14]:
patients['AdmissionDate'].head(5)

0   2025-03-22
1   2025-03-31
2   2025-01-08
3   2025-04-03
4   2025-06-03
Name: AdmissionDate, dtype: datetime64[ns]

In [15]:
patients['DischargeDate'].tail(5)

195   2025-05-02
196   2025-07-08
197   2025-06-04
198   2025-07-05
199   2025-03-09
Name: DischargeDate, dtype: datetime64[ns]

In [18]:
patients['Length_of_Stay'] = (patients['DischargeDate'] - patients['AdmissionDate']).dt.days

In [19]:
patients['Length_of_Stay'].head(5)

0    13
1     2
2    64
3     2
4     1
Name: Length_of_Stay, dtype: int64

### Feature Engineering

In [21]:
patients['OutcomeName']

0        Recovered
1      Complicated
2        Recovered
3        Recovered
4        Recovered
          ...
195       Deceased
196       Deceased
197    Complicated
198    Complicated
199       Deceased
Name: OutcomeName, Length: 200, dtype: object

In [22]:
patients['OutcomeEncoded'] = patients['OutcomeName'].map({'Recovered' : 0, 'Complicated' : 1, 'Deceased' : 1})

In [24]:
patients['OutcomeEncoded'].head(10)

0    0
1    1
2    0
3    0
4    0
5    0
6    1
7    0
8    1
9    1
Name: OutcomeEncoded, dtype: int64

- Creating Risk Indicator

In [37]:
patients['HighRisk'] = np.where((patients['Age'] > 65) | (patients['OutcomeName'].isin(['Complicated', 'Deceased'])), 1,0)

In [38]:
patients['HighRisk']

0      1
1      1
2      0
3      0
4      1
      ..
195    1
196    1
197    1
198    1
199    1
Name: HighRisk, Length: 200, dtype: int64